apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: git-service
type: Opaque
data:
  POSTGRES_PASSWORD: $(echo -n "postgres" | base64)
  POSTGRES_USER: $(echo -n "postgres" | base64) 